name: Docker Image CI

on:
  push:
    branches: [ "bistu-dev" ]
  pull_request:
    branches: [ "bistu-dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup yarn
      run: yarn dev:setup
    
    - name: Build the Docker image
      run: |
        cd docker
        docker-compose build

    
    - name: Login to Huawei Cloud Container Registry
      run: |
        hmac_result=$(printf "WQNYRKPMYGBRONLHYHL1" | openssl dgst -binary -sha256 -hmac "V8BvaT9CwdRDCBnt9w8qDoL54hPnfbg8tf6AypUA" | od -An -vtx1 | sed 's/[ \n]//g' | sed 'N;s/\n//')
        docker login -u ap-southeast-1@WQNYRKPMYGBRONLHYHL1 -p "$hmac_result" swr.ap-southeast-1.myhuaweicloud.com

    - name: Make new tag and push
      run: |
        export ds=$(date +%s)
        docker tag vector-admin:latest swr.ap-southeast-1.myhuaweicloud.com/sunny/vector:d${ds}
        docker push swr.ap-southeast-1.myhuaweicloud.com/sunny/vector:d${ds}
